<a href="https://colab.research.google.com/github/KAji-SaputraRomadhon/PM-Turi2-prepprocessing-kurniawanajisaputraromadhon/blob/main/PM_P4_Kurniawan_aji_saputra_romadhon_2488010027.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Dataset

In [ ]:
import pandas as pd
import numpy as np

# Dataset karyawan (sengaja mengandung masalah kualitas)
data = {
    'usia'      : [25, 32, np.nan, 45, 28, 51, 38, np.nan, 29, 41],
    'pendapatan': [4_000_000, 7_500_000, 5_200_000, 12_000_000, 4_800_000,
                   15_000_000, 8_100_000, 6_300_000, np.nan, 9_900_000],
    'pendidikan': ['SMA','S1','SMA','S2','SMA','S2','S1','S1','SMA','S2'],  # ordinal
    'kota'      : ['Bandung','Jakarta','Bandung','Surabaya','Jakarta',
                   'Surabaya','Jakarta','Bandung','Bandung','Jakarta'],    # nominal
    'membeli'   : ['Tidak','Ya','Tidak','Ya','Tidak','Ya','Ya','Tidak','Tidak','Ya']  # target
}
df = pd.DataFrame(data)
print("Nilai hilang sebelum imputasi:")
print(df.isna().sum())
df

Nilai hilang sebelum imputasi:
usia          2
pendapatan    1
pendidikan    0
kota          0
membeli       0
dtype: int64

   usia  pendapatan pendidikan      kota membeli
0  25.0   4000000.0        SMA   Bandung   Tidak
1  32.0   7500000.0         S1   Jakarta      Ya
2   NaN   5200000.0        SMA   Bandung   Tidak
3  45.0  12000000.0         S2  Surabaya      Ya
4  28.0   4800000.0        SMA   Jakarta   Tidak
5  51.0  15000000.0         S2  Surabaya      Ya
6  38.0   8100000.0         S1   Jakarta      Ya
7   NaN   6300000.0         S1   Bandung   Tidak
8  29.0         NaN        SMA   Bandung   Tidak
9  41.0   9900000.0         S2   Jakarta      Ya

## Langkah 1

In [ ]:
df['usia'] = df['usia'].fillna(df['usia'].median())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].median())

display(df)

   usia  pendapatan pendidikan      kota membeli
0  25.0   4000000.0        SMA   Bandung   Tidak
1  32.0   7500000.0         S1   Jakarta      Ya
2  35.0   5200000.0        SMA   Bandung   Tidak
3  45.0  12000000.0         S2  Surabaya      Ya
4  28.0   4800000.0        SMA   Jakarta   Tidak
5  51.0  15000000.0         S2  Surabaya      Ya
6  38.0   8100000.0         S1   Jakarta      Ya
7  35.0   6300000.0         S1   Bandung   Tidak
8  29.0   7500000.0        SMA   Bandung   Tidak
9  41.0   9900000.0         S2   Jakarta      Ya

## Langkah 2

In [ ]:
X = df.drop(columns=['membeli'])
y = df['membeli']

display(X)
display(y)

   usia  pendapatan pendidikan      kota
0  25.0   4000000.0        SMA   Bandung
1  32.0   7500000.0         S1   Jakarta
2  35.0   5200000.0        SMA   Bandung
3  45.0  12000000.0         S2  Surabaya
4  28.0   4800000.0        SMA   Jakarta
5  51.0  15000000.0         S2  Surabaya
6  38.0   8100000.0         S1   Jakarta
7  35.0   6300000.0         S1   Bandung
8  29.0   7500000.0        SMA   Bandung
9  41.0   9900000.0         S2   Jakarta

0    Tidak
1       Ya
2    Tidak
3       Ya
4    Tidak
5       Ya
6       Ya
7    Tidak
8    Tidak
9       Ya
Name: membeli, dtype: object

## Langkah 3

In [ ]:
# Ordinal encoding pendidikan
X['pendidikan'] = X['pendidikan'].map({
    'SMA': 0,
    'S1': 1,
    'S2': 2
})

# One-hot encoding kota
X = pd.get_dummies(
    X,
    columns=['kota'],
    dtype=int
)

# Encoding target
y = y.map({
    'Tidak': 0,
    'Ya': 1
})

display(X)
display(y)

   usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
0  25.0   4000000.0           0             1             0              0
1  32.0   7500000.0           1             0             1              0
2  35.0   5200000.0           0             1             0              0
3  45.0  12000000.0           2             0             0              1
4  28.0   4800000.0           0             0             1              0
5  51.0  15000000.0           2             0             0              1
6  38.0   8100000.0           1             0             1              0
7  35.0   6300000.0           1             1             0              0
8  29.0   7500000.0           0             1             0              0
9  41.0   9900000.0           2             0             1              0

0    0
1    1
2    0
3    1
4    0
5    1
6    1
7    0
8    0
9    1
Name: membeli, dtype: int64

## Langkah 4

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

display(X_train)
display(X_test)

   usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
0  25.0   4000000.0           0             1             0              0
7  35.0   6300000.0           1             1             0              0
2  35.0   5200000.0           0             1             0              0
9  41.0   9900000.0           2             0             1              0
4  28.0   4800000.0           0             0             1              0
3  45.0  12000000.0           2             0             0              1
6  38.0   8100000.0           1             0             1              0

   usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
8  29.0   7500000.0           0             1             0              0
1  32.0   7500000.0           1             0             1              0
5  51.0  15000000.0           2             0             0              1

## Langkah 5

In [ ]:
# Langkah 5 — Penskalaan fitur

from sklearn.preprocessing import StandardScaler

num = ['usia', 'pendapatan', 'pendidikan']

sc = StandardScaler()

X_train[num] = sc.fit_transform(X_train[num])
X_test[num] = sc.transform(X_test[num])

display(X_train.round(4))
display(X_test.round(4))

     usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
0 -1.5887     -1.1694     -1.0290             1             0              0
7 -0.0441     -0.3251      0.1715             1             0              0
2 -0.0441     -0.7289     -1.0290             1             0              0
9  0.8826      0.9964      1.3720             0             1              0
4 -1.1253     -0.8758     -1.0290             0             1              0
3  1.5004      1.7672      1.3720             0             0              1
6  0.4192      0.3356      0.1715             0             1              0

     usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
8 -0.9709      0.1154     -1.0290             1             0              0
1 -0.5075      0.1154      0.1715             0             1              0
5  2.4271      2.8685      1.3720             0             0              1

## Langkah 6

In [ ]:
# Langkah 6 — Verifikasi

print("Missing values:")
print(X_train.isnull().sum())
print(X_test.isnull().sum())

print("\nData types:")
print(X_train.dtypes)

print("\nStatistik data training:")
display(X_train.describe().round(4))

Missing values:
usia             0
pendapatan       0
pendidikan       0
kota_Bandung     0
kota_Jakarta     0
kota_Surabaya    0
dtype: int64
usia             0
pendapatan       0
pendidikan       0
kota_Bandung     0
kota_Jakarta     0
kota_Surabaya    0
dtype: int64

Data types:
usia             float64
pendapatan       float64
pendidikan       float64
kota_Bandung       int64
kota_Jakarta       int64
kota_Surabaya      int64
dtype: object

Statistik data training:

,usia,pendapatan,pendidikan,kota_Bandung,kota_Jakarta,kota_Surabaya
count,7.0000,7.0000,7.0000,7.0000,7.0000,7.0000
mean,0.0000,0.0000,-0.0000,0.4286,0.4286,0.1429
std,1.0801,1.0801,1.0801,0.5345,0.5345,0.3780
min,-1.5887,-1.1694,-1.0290,0.0000,0.0000,0.0000
25%,-0.5847,-0.8023,-1.0290,0.0000,0.0000,0.0000
50%,-0.0441,-0.3251,0.1715,0.0000,0.0000,0.0000
75%,0.6509,0.6660,0.7717,1.0000,1.0000,0.0000
max,1.5004,1.7672,1.3720,1.0000,1.0000,1.0000

## LATIHAN MANDIRI

1. Ganti imputasi usia menjadi mean; bandingkan hasilnya.

In [ ]:
df_mean = df.copy()

df_mean['usia'] = df_mean['usia'].fillna(df_mean['usia'].mean())

display(df_mean)
print("Mean usia:", df_mean['usia'].mean())

   usia  pendapatan pendidikan      kota membeli
0  25.0   4000000.0        SMA   Bandung   Tidak
1  32.0   7500000.0         S1   Jakarta      Ya
2  35.0   5200000.0        SMA   Bandung   Tidak
3  45.0  12000000.0         S2  Surabaya      Ya
4  28.0   4800000.0        SMA   Jakarta   Tidak
5  51.0  15000000.0         S2  Surabaya      Ya
6  38.0   8100000.0         S1   Jakarta      Ya
7  35.0   6300000.0         S1   Bandung   Tidak
8  29.0   7500000.0        SMA   Bandung   Tidak
9  41.0   9900000.0         S2   Jakarta      Ya

Mean usia: 35.9

2. Gunakan MinMaxScaler (0–1) sebagai ganti StandardScaler; tampilkan describe().

In [ ]:
from sklearn.preprocessing import MinMaxScaler

X_minmax = X.copy()

X_train_mm, X_test_mm, y_train_mm, y_test_mm = train_test_split(
    X_minmax,
    y,
    test_size=0.3,
    random_state=42
)

num = ['usia', 'pendapatan', 'pendidikan']

mm = MinMaxScaler()


X_train_mm[num] = mm.fit_transform(X_train_mm[num])
X_test_mm[num] = mm.transform(X_test_mm[num])


print("Statistik X_train setelah MinMaxScaler:")
display(X_train_mm.describe().round(4))

print("Statistik X_test setelah MinMaxScaler:")
display(X_test_mm.describe().round(4))
display(X_train_mm.round(4))

Statistik X_train setelah MinMaxScaler:

,usia,pendapatan,pendidikan,kota_Bandung,kota_Jakarta,kota_Surabaya
count,7.0000,7.0000,7.0000,7.0000,7.0000,7.0000
mean,0.5143,0.3982,0.4286,0.4286,0.4286,0.1429
std,0.3497,0.3678,0.4499,0.5345,0.5345,0.3780
min,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
25%,0.3250,0.1250,0.0000,0.0000,0.0000,0.0000
50%,0.5000,0.2875,0.5000,0.0000,0.0000,0.0000
75%,0.7250,0.6250,0.7500,1.0000,1.0000,0.0000
max,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000

Statistik X_test setelah MinMaxScaler:

,usia,pendapatan,pendidikan,kota_Bandung,kota_Jakarta,kota_Surabaya
count,3.0000,3.0000,3.00,3.0000,3.0000,3.0000
mean,0.6167,0.7500,0.50,0.3333,0.3333,0.3333
std,0.5965,0.5413,0.50,0.5774,0.5774,0.5774
min,0.2000,0.4375,0.00,0.0000,0.0000,0.0000
25%,0.2750,0.4375,0.25,0.0000,0.0000,0.0000
50%,0.3500,0.4375,0.50,0.0000,0.0000,0.0000
75%,0.8250,0.9062,0.75,0.5000,0.5000,0.5000
max,1.3000,1.3750,1.00,1.0000,1.0000,1.0000

   usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
0  0.00      0.0000         0.0             1             0              0
7  0.50      0.2875         0.5             1             0              0
2  0.50      0.1500         0.0             1             0              0
9  0.80      0.7375         1.0             0             1              0
4  0.15      0.1000         0.0             0             1              0
3  1.00      1.0000         1.0             0             0              1
6  0.65      0.5125         0.5             0             1              0

3. Tambahkan kolom kategorikal baru dan terapkan one-hot encoding.

In [ ]:
df_kategori = df.copy()

df_kategori['status'] = [
    'Tetap',
    'Tetap',
    'Kontrak',
    'Tetap',
    'Kontrak',
    'Tetap',
    'Tetap',
    'Kontrak',
    'Kontrak',
    'Tetap'
]

display(df_kategori)

# One-hot encoding kolom status

df_kategori = pd.get_dummies(
    df_kategori,
    columns=['status'],
    dtype=int
)

display(df_kategori)

   usia  pendapatan pendidikan      kota membeli   status
0  25.0   4000000.0        SMA   Bandung   Tidak    Tetap
1  32.0   7500000.0         S1   Jakarta      Ya    Tetap
2  35.0   5200000.0        SMA   Bandung   Tidak  Kontrak
3  45.0  12000000.0         S2  Surabaya      Ya    Tetap
4  28.0   4800000.0        SMA   Jakarta   Tidak  Kontrak
5  51.0  15000000.0         S2  Surabaya      Ya    Tetap
6  38.0   8100000.0         S1   Jakarta      Ya    Tetap
7  35.0   6300000.0         S1   Bandung   Tidak  Kontrak
8  29.0   7500000.0        SMA   Bandung   Tidak  Kontrak
9  41.0   9900000.0         S2   Jakarta      Ya    Tetap

   usia  pendapatan pendidikan      kota membeli  status_Kontrak  status_Tetap
0  25.0   4000000.0        SMA   Bandung   Tidak               0             1
1  32.0   7500000.0         S1   Jakarta      Ya               0             1
2  35.0   5200000.0        SMA   Bandung   Tidak               1             0
3  45.0  12000000.0         S2  Surabaya      Ya               0             1
4  28.0   4800000.0        SMA   Jakarta   Tidak               1             0
5  51.0  15000000.0         S2  Surabaya      Ya               0             1
6  38.0   8100000.0         S1   Jakarta      Ya               0             1
7  35.0   6300000.0         S1   Bandung   Tidak               1             0
8  29.0   7500000.0        SMA   Bandung   Tidak               1             0
9  41.0   9900000.0         S2   Jakarta      Ya               0             1

4. Jelaskan mengapa fit_transform pada latih tetapi hanya transform pada uji.

fit_transform() digunakan pada data training karena scaler perlu mempelajari parameter dari data training, seperti nilai rata-rata dan standar deviasi pada StandardScaler.

## Refleksi

1. Mengapa urutan 'split dulu, baru scaling' penting?

Untuk mencegah terjadinya data leakage. Data dibagi menjadi data latih dan data uji terlebih dahulu. Setelah itu, StandardScaler melakukan fit_transform() hanya pada data latih untuk mempelajari parameter scaling. Data uji kemudian hanya menggunakan transform() dengan parameter yang sudah diperoleh dari data latih.

2. Kapan label encoding dan kapan one-hot encoding?

Label encoding digunakan ketika kategori memiliki urutan atau tingkatan (ordinal).
Sedangkan one-hot encoding digunakan untuk kategori nominal, yaitu kategori yang tidak memiliki tingkatan.

3. Apa perbedaan normalisasi dan standardisasi?



* Normalisasi merupakan proses mengubah nilai data ke rentang tertentu, misalnya 0 sampai 1.
* Standardisasi merupakan proses mengubah data berdasarkan rata-rata dan standar deviasi.